DOC: Improve REST method documentation
veraPDF/veraPDF-rest pull request #146
Opened 2024-01-29 09:54 UTC by carlwilson

- fixed `@Schema` annotations for correct return types;
- improved documentation of methods; and
- added return examples where appropriate.

TODO: Fix the validation method documentation, which requires some refactoring.

2024-01-29 15:05 UTC, MaximPlusov requested changes
I сan make commits with some changes to branch doc/swagger-dox myself

2024-01-31 07:13 UTC, carlwilson commented on src/main/java/org/verapdf/rest/resources/ProfileResource.java
> +     *                  3b, 3a, 3u, 4, 4e, 4f or ua1)
Done

2024-01-31 07:13 UTC, carlwilson commented on src/main/java/org/verapdf/rest/resources/ProfileResource.java
> +                    "(1b, 1a, 2b, 2a, 2u, 3b, 3a, 3u, 4, 4e, 4f or ua1") @PathParam("profileId") String profileId) {
Done

2024-02-01 08:35 UTC, MaximPlusov approved these changes

2024-02-08 12:43 UTC, merged